### ISSUE TITLE
Data Processing Details about Taobao Dataset

### ISSUE THREAD

**Issue by wendy2003888** [Z-Y-Zhang/one_epoch_phenomenon#4]
Hi Zhao Yu,
Congrats on paper acceptance! I am Wendy from snapchat working together with Zihan. I am working on reproducing the result on Taobao dataset.

I have a few questions about data processing
1. How do you select the positive samples and negative samples from the dataset?
I selected click behavior samples only but the cardinality can't match the number mentioned in your paper as well as CAN's . And the number mentioned in the paper seems to be different as what is mentioned in the dataset page as well.
paper number
<img width="1212" alt="Screen Shot 2022-12-13 at 9 20 46 AM" src="https://user-images.githubusercontent.com/9080562/207400943-a1fa4b12-d28c-4e7d-8e43-3aea83e5e7bf.png">

Mine number on click samples only
<img width="424" alt="Screen Shot 2022-12-13 at 9 21 45 AM" src="https://user-images.githubusercontent.com/9080562/207401165-4a31610b-aa7c-418c-9534-26cf22c52560.png">

Full dataset  matches numbers mentioned in dataset page
<img width="424" alt="Screen Shot 2022-12-13 at 9 22 31 AM" src="https://user-images.githubusercontent.com/9080562/207401381-f9d2f177-5850-4cd0-b2f3-48d9aed577d9.png">
<img width="743" alt="Screen Shot 2022-12-13 at 9 23 26 AM" src="https://user-images.githubusercontent.com/9080562/207401663-b08fecdf-fd49-4ddc-bfee-f29e41b4703b.png">

CAN paper number
<img width="635" alt="Screen Shot 2022-12-13 at 9 24 29 AM" src="https://user-images.githubusercontent.com/9080562/207401993-d2377d30-8aeb-4b0f-b3de-05ab4a6326ba.png">

2. How did you handle the history sequence?
my understanding is that each sample is group by user_id, item_id.
2.1 Did the his_item_ID sequences contain the clicked item_ids happens before current item_id timestamp only? Or it contains ids from all behavior types?
2.2 How did you handle duplicate item_ids?

3. How did you split the train test in taobao dataset? 
Is it 0.1 split ratio?

Looking forward to your reply.
Thank you

**Comment by Z-Y-Zhang** [comment]
Hi Wendy,

Since the public data is quite different from our production practice, I focused on the production data during the experiment. As for the public data, I directly used the existing preprocessing code and did not care about the details. Since I have left Alibaba and the experimental environment has been deleted (because of the privacy policy), I am sorry that it is difficult for me to answer too detailed questions. Anyway, I try to give some information and hope it can help you.

The following is my personal understanding and cannot be guaranteed to be 100% correct.
1 I feel that your use of click samples can match our data, and there will be slight differences because there is no fixed random seed. The difference with CAN is that we exclude userid.
2.1 The his_item_ID sequences contain the clicked item_ids happens before current item_id timestamp only.
2.2 The duplicate item_ids are preserved
3 Yes

According to my understanding, the above problems should not affect the one epoch phenomenon, that is to say, no matter which method is chosen, the one epoch phenomenon will appear.

**Comment by wendy2003888** [comment]
Thanks Zhao Yu. We Found the data processing logic of  [MIMN paper](https://github.com/UIC-Paper/MIMN) and checked the details there. 
Yeah, we also observed one epoch phenomenon on a few other open-source datasets.
Thanks again for response.
Best wishes to your new adventure. Happy lunar new year!
